version: '3'

services:
  db:
    build:
      args:
        - DB_LANG=ja_JP
    image: postgres:15.3
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=passw0rd
    volumes:
      - ./init:/docker-entrypoint-initdb.d
