version: '3'

services:
  postgres:
    build:
      args:
        - DB_LANG=ja_JP
    image: postgres:15.3
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_DB=SAMPLE
    restart: always

